language: node_js

notifications:
  email: false

sudo: false

node_js:
- lts/*

before_script:
- npm install

script:
- gulp build

# Cache setup
cache:
  directories:
  - node_modules

# Decrypt private key and add the known hosts
before_install:
- openssl aes-256-cbc -K $encrypted_47d2dcf4817b_key -iv $encrypted_47d2dcf4817b_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- cat .travis/known_hosts >> $HOME/.ssh/known_hosts

deploy:
  provider: script
  script: "./.travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: production
