language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

before_script:
- npm install

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: T1LSf0wL6V/nBr2mXaKdSPyfcnyqpFzO7fI//gB5u9ojsIhz+lk+W6lVi41H+cStCZPlG8o911ivCZ9N5WcxnMF3Mv9oJIbzxSFTdWVQeNTxSf4NBXb222nzMbo/Qew7xa/uJZ1QBNvjCsrt1I8+BZXJ78j88ijRk8EuVGVXy1pWvh5gWqOT11HOeNcmoBO9vu2ZzxN+bq4sG0xmsIvryPLeDM2gBXi7SFfJVczIU42hMvk9U4iYzcS0R9cGRmLvPjcKkPCjKL9Wu9XMljkqwi7txVJjmDjRWywEQ6VE2GB2cznOtbeVLgz9vxOz+3OL9jBp6GZ4nkQbhBxd6bi+U6ATPrtL8RaddxILRmkhVbryrLbnK8qociIzUH3Pw1UWEpL3pMynMCeVuOxJe1SD1VcrF+lsAwNMvMa/HYk1u++gfaaULW6Oacz5sOIVOqUd+HaRKxPBrgpUXmSKUB6+BoDC5JF/hlHCkkTBCY9tAloRP46aNgyzfrzV+3LvZ2p+oOmN81cAqCdvrFDsvKQWGzhwt+3wGbH1VJMlQ/3+/g34ahzuQ1dJtzFsGHavITkXv9Ic06QgSOpen02tIOsvB4Sz/TJPthVmOkzcCfySkP9H04BX33p218RdON1P4wYvMiNKog+1T5cpg1ZeoPpVQfM/0Z9kcJ4ecK4tnKg/naU=
  - secure: aPYlfJ8p/zyVQ5/pc/o+hWKiof/vJOQTsXcdgxubB5HbM3HmyMV7lD44Esc2Vm6ohvX7xuUGawJFTgblZfR85dCbBae1wX7SoCpHkhJhPbQAE54ohICE5o4KI1TJI+epktMmn5tRXfRifkDUfDpH4EqpDo4EkjxPOTXQ1sjBT+HeoNXDca4UJWVDNxErBZRzYeInBwxEyeK2zmA4J6Fz5hOp3Iaee0AVM9GT0dG7HLi1F/9Cdm0WreIQ95Z3/Hsdp6sH/0KIR9fAYUs+oyd9DrY8y0rk4dZH2HhTZUxT5Q/XkpCF+FtzgZ1MenD09+LFqgGFaG650PyKRRrmg7R8MheUOSg1CIokPkZbGmE/ByHFjpwtrGkSmly3nRWSMyrcYQsGwtHSJk/VhraND6vncksXG05APsuFPmNPWT+l5PyfuTJBq2r+ocrmS1508Ab220sodV6NX19V8wWwKQ/gX8RULHi1YHckph3OdKdQPbFQ68b+4RYsGUOo820bYGShwCcWKbRvPRMQIGEpntGrkhqlP8getl7UTzApA29bv1UvzuLi8aHvVeTsttALX6StRp9ZCZIFtm+0QnkabRvmaQwEygM16zmdMiCgaZ40bW6ch70Uo2kiES7Y/8BqKVi4yJM/jEj2Vbq/DgiqVzSFWbOSTpp4UZLhgyQPv6LwQ1w=
  - secure: JetM/cfLfeWEjMfzme/9xDRoIOLIEoBdr3pQtUYZ4jq2BKOHg5pZeXtznn4q+cU416WmtMB6lL8ICw6rl27EAQ28B2ETbx6CyNYPvVyg0u7UQ+f38C65i9vPk/kAn1NmYs0OncX642ONN1aXcA1QKMoCdVh63RBmg9PMVL19yDjrriq87SY2HrJsSKJ0b+H7LlndWZisNsWQfmryLMgK4BEaPTas0strZc8rrovFhNIs0gAA5ERwngOXIuoslp96l3nBExtaxoxWSqj3RY1jyzKymZPJL2MCtgLTIqsjsTrEFgP+wP6fI9QDSBZRLEKWtG5zzYgohGSetwxydhZWJ+PLsBrNuLCr+iBKSx3AD+jaqSToWiltFxxOfE/B8z93WIAVN6W7aqrmK2RncDWe3BDFLz6kqBXNgozmd6+1pPSTIgQd7MGS+CzIP2FVNSV5cksh/rOnpJpe2tBwHT1W241hZW5XAFGK2Zh4MJtR50oaU/r7pOcHEu/9wGxZe4yc8a2amosAnXiSED6iUDGFIkS0P0baXc2KGFb21B1GAPwphr6S29Zr2rfYHH0IbVjsy69OCNzHgmNT9wmZwwVzfNGcyHRA4soetMN8YifPjTxxpzykddzfMlMSyem4o9EoTZyyWnatj+XBEkCcb8/wAT/3+YS0jjG9OyC7x9ApsP4=
  - secure: 4onhP4sv3wDVTPeS4y7RpOm4M/2x9IBlzEvMwNvrYplI4dcf4vTQoBIPKPhvv8SYOo36eDhQ2c1y3yYMGwK6kH6DpbOs869OCvD7SrllvmqJ7WW3v8LO3corHEArWrmMMBU8S2Wv8E/9VtqsU+BrL1CnzFAcI2Xfyv/hUXBZq3vumXy+1TS/nB14EdOjUWv5Kay+8z9cmKfVnSElwBlnJD2CgJH6+oZcRoe4F91mMCE3nATlicMWQqIRBcwV15BxkzFMNJ4EGThYTGWU1jgHV6gYtBNdXqvavUjOPX8HX/GEZsUdKzuFmuJtpO2X9coME5QEQ0PrTNCjm4qBL5yzjOSDBw89aRQCRPdYcNgjorZL3TBGHDVQkmELNtwDSxVMIXTuvLL+IeEaL6IjJAgP6b0slpgTNSP5HjE19+FbRsq0MKKcNI1ZFSFxk4Q10oswDigFZwCUhR4ACauV1NoJ6W5c9Idz82BG+gXG6qMqqsoVVtPYhTA0jPa8536R5BfPRXH4A7Sq+L4gcrjws/aA3zQTFuLNaTHrWgoNC63wMxrrplOG9ENOIMJEhUwhCop8CmYDKe55XccaQqWcvbK9JQC7gTJw3s1aNJ3fdeacAIumOoTEx9w74rRu7f5Qyy2RGInDTnWLhb4mBTFRww9j20YpBc9twxMxOvbQnTl2Nbw=
