language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

before_script:
- npm install

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: Exki8qm6OiLuVLsIAJjnwVMeSPkAK1CG6KKyVS6siqoRuUi/RW6mKpNdGYMa4mzbbo6DJRVAtxyLXJLJhkpxqtp4rLCXXAnk6rqLww9bvpD/G08voVXlCjq3w6ZDrUyw4oaDqcPMpwe+VP01EHj41Xz3ytrrbKgB8CHB0QXNa0nwTcJu8b+dBMzedk3gDQF7dxrWVq9bpZS8Fyla11E7eYDruBwlO/KhJvzaVcMjLXwxnr4ewK8S43W+O8H1B3t514i0ez2oiOET9v5ytgMdx8iIrjEsr29LsN/R1LJJQS6Yl+xQZ16qSBgV8bCDjT4M6EcRBhkvBAaQ3cp71Exh58Ws1AHfq4PUVnPx0lW/shgAfEerM6B7W2BP7hRN3MJMOAUrw80b38nww8gm3fTHlKsK0v0rgxiGcE2FYdgXry6oRFHvK6m/7Xl6jT500ssV17VFX4c6u2yRFbMlJVzCJFRVcpytm8h/Ibztcx5JzSgBhYZBt23AOld+57mJ8pNatdmdm86yN5kja1UlpVu1lHme/MIeYgchaspraszdz+BTBukE64MCiCqoRcUimkUNQbhuXZJLscNpDUGdH1Mjf83lWJgNuAE+YUu5SH8iwgX1Nwqm/Upsp2HES3UGKRfiMAnu6gY34iqVP+uzRk5F4DhqcyHwDfegZrBMavFVGMM=
  - secure: 5206QF/qXIzviaROOxhWS5gdqMSqvpURtk59yXxqaG59sb/h7t7rgIxZaIlYTlsYpigUEJ7/sgnfaJU8sbdHlkTVwhm0Nr8udJnT0DBA8THc3g9U603hUxG7/qJhOsjEOPstHOkqb2R+1GD4xLw3wMytq3PHy7f1iJFm7bTuhuzDTq4LZdkk9n1QyhgYJcMdXaw5CDIpF9B3j/4+2GC5YM8EyVQQOQqynNvz3wqmSa01Vkn6Ht6rOycLuX2i+D8xXNFqyfPbTPJrqWrQGqe5ipj75HqYjZUYkYrgGCACLA/a/sYCiWea2chPDeSR1bQyy2ovDv+vZgUbqtZFD4hbs4pCPb5Ns7gPnh9IdhLeG21QL1FupKtk+u3nHGlvWT1gDFAtbFsUU1bxqwXM57M3nHWS4sGDrmRjgssBYK3qBydRq7OabF6kt+/BaVkvyR6YR+M9Xku48xOZyBOMeKP6T1hyESCphOJvBo1brdS1MlgwTmMJmmiiuYJO6N5JW9fxSX7cxz3CnZLwE8rI43N5IlVSMzX0t4mVJRZd0lBpp1OOIszI88bFI2TdSbK7SRuTifmF+Vbn1RlTeFDJ+MdxETY0+Sa11eWDtpxWxzHbotbTWWczKsx3zAvVoEn6bTZun6zua/2QBoto6UXfm0Cio10CuX+SogFEwgUNjB0f8LE=
  - secure: znxs+V3GXuVLWj/9vj8wHHbfhHXkjS5QLzf80RT/keSLPVZVmaWCxLUP+w4MOqqyFv23QADLAA2qTTx9MK6nTPdpuHU0GKbbQmrIwisMdertmTnhcwg1KocgsysqmoD+Jb4kpnM47evwJgJHV0icVb18vgDg1QCy3jSPzvapFwPYrCHZvs4yUZgkV6B9uB+ENHNmbCP5iIjtdTrCkE/P7iwA4S9M5aug3gAHU0C5OIZEhpMnX1vc1wvQ7dOHK11oGD2hmPo8ZWR+5lZBvFCjijycoy7yjrGe4ewad6AyC2fnlj5tUgj8lVud2O8SBhd7T58zAhduijmzwZre49jitcN1tE9YCRB2xg7wDXCSObS8Tm2fn05iMwaakMLT3931v1ClNs06JQQAmLbRWhBlLjxNecfU1DewdL+j//YRZE3sm14HH7K3OMk9s69c/0JqkWnsfT27tieUncWBeHk+zKAiDraCdB5MDLIk6etek3l6CKGKPvGBnGWmGZKk1p0b0q6n7+g7T0NiIQyB/oMrTHyk5kwnR3t4fWEhoFtLom5VcICmg71l8t6Gg2w5OYPmEL6osIwLnq3OGpa6vBtciqRwK+Ah6tvb0aTqY1LsPJ7K5+CQk7Br4CV0y+yEpKnNI23K2+Mq92CrTZr5JzIs0xTq/lNhT9C4hzU9d/wENqs=
  - secure: a3SvjMeUztpGRa5C4i6ngzoikvjyZ6ZhfYtrECVIQuprAcYAdIfV6uNgxu384CPS30BxCtF36YBc6Rbob942JoCDKboMQ4gIRsR3fpSR8qvTSvEsYB+lykc9O+V0sD0PXGpb2HWyGq9VWGodzVH+agvJBoEjjnJWz/+OjUd552YnZPyvhNhKMRZZYOE2A2Vs4kgmpp5RfuAi+Z/HpDhyvbMd90Otny8axfKToyywTLe/NesuPwKr5kV9qO9rVACYbkHYlvOdqV37ZCwmPtAJW7X/Yc0FevIOhv5TA/6xwxWWZMhNdI2xLdlSvIm3WzYX0WzyztqX+ilEVYey16NvAaQNLKFoC1ZuhqboldZJDc3WuwbyI+TiAc1gSe9W3rq0pqtPZofaPZD5MhtKFoIks1RjcmWU4hXyb53oTKA+O0uFkLPae9doqv5C+erS9lO8QrRt4s1YK/HByNaN5KZOaeyV6e9DCdHVx+hVbtBUQvELp3itlgkzapfQ5oTZzoLfDhMcEGTk9Rc7RKY2Uph5rMAgzZixg1V7UnfIysPW1ElABdwWFNEHm2n4ygwGmZEfOlaNAT+0UnhTxg+xS6xuGlRKysxMA7xt8wsSOACB7xpFw+gU0H03lx00AcvegWlyfVKz4fxfbJX/tG70r5gK3YB+c35ldw8cTqT1of/2co0=
